### ISSUE TITLE
GPG validation issue

### ISSUE THREAD

**Issue by adeleglise** [geerlingguy/ansible-role-puppet#1]
Hi,
I am using your role for a long time now, and it always worked like a charm. However it seems that the GPG key has been deprecated and can no longer be used.

```
TASK [geerlingguy.puppet : Add Puppet Labs repositories.] **********************************************************************************************************************************************************************************************************************************
fatal: [redacted]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for puppet6-release-6.0.0-3.el8.noarch"}
fatal: [redacted]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for puppet6-release-6.0.0-3.el8.noarch"}
```

Ansible version
```
ansible --version
ansible 2.9.14
```

Role version 
```
geerlingguy.puppet (2.0.0)
```

OS
```
cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)
```

**Comment by geerlingguy** [comment]
Note that the rpm that's used in this role currently defaults to one compatible with CentOS 7:

```yaml
puppet_yum_rpm: "https://yum.puppet.com/puppet6/puppet6-release-el-7.noarch.rpm"
```

I haven't yet updated this role to make sure it works with CentOS 8 or added a test for CentOS 8.

**Comment by geerlingguy** [comment]
Interesting... apparently their latest GPG key (https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406) is not working for the RPM repos (it works for deb), I have to switch to https://yum.puppet.com/RPM-GPG-KEY-puppet, which seems to actually work.

**Comment by geerlingguy** [comment]
Fixed in version 3.0.0. Thanks for raising the issue!

**Comment by adeleglise** [comment]
Wow thanks a lot @geerlingguy !! I'm a big fan :p Thanks again for your work.

**Comment by adeleglise** [comment]
It seems that using the repo address `"https://yum.puppet.com/puppet6/puppet6-release-el-7.noarch.rpm"` provokes a dependency error :
```
 Problem: package ruby-facter-3.14.2-3.el8.x86_64 requires facter(x86-64) = 3.14.2-3.el8, but none of the providers can be installed
  - package puppet-agent-6.18.0-1.el8.x86_64 obsoletes facter < 1:3.0.0 provided by facter-3.14.2-3.el8.x86_64
  - cannot install the best update candidate for package ruby-facter-3.14.2-3.el8.x86_64
  - cannot install the best update candidate for package facter-3.14.2-3.el8.x86_64
```
I tried using : `https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm` instead and it resolves the missing packages.
